### ISSUE TITLE
data link not working

### ISSUE THREAD

**Issue by tarizshahid** [deepankarvarma/Age-and-Gender-Detection-OpenCV--Keras--TensorFlow#1]
https://drive.google.com/u/0/uc?id=0BxYys69jI14kYVM3aVhKS1VhRUk&export=download

the following URL is not accessible please allow.
 sharing permissions  -> anyone with link 
 Thanks

**Comment by deepankarvarma** [comment]
Hi Tariz, this link is not under my control, and it is invalid as the dataset seems to be removed from this link. You can use the following link :- https://www.kaggle.com/jangedoo/utkface-new
